version: '3.8'

services:
  app:
    image: amazoncorretto:21
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./gradlew bootRun
    environment:
      DATASOURCE: jdbc:postgresql://db:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  db:
    image: postgres:14-bullseye
    container_name: menu-pg
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INIT_DB_ARGS: --encoding=UTF-8
